---
version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - intrange
    - lll
    - misspell
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    depguard:
      rules:
        imports:
          deny:
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package.
            - pkg: "github.com/sirupsen/logrus"
              desc: use log/slog for structured logging instead of logrus.

    dogsled:
      max-blank-identifiers: 3

    errorlint:
      asserts: false

    funlen:
      lines: -1
      statements: 60

    goconst:
      min-len: 2
      min-occurrences: 3

    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - typeUnparen
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style

    gocyclo:
      min-complexity: 35

    godox:
      keywords:
        - FIXME

    gosec:
      excludes:
        - G109
        - G115
        - G204
        - G303

    govet:
      enable:
        - nilness
        - shadow

    lll:
      line-length: 170

    misspell:
      locale: US

    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: true

    revive:
      rules:
        - name: indent-error-flow
        - name: unexported-return
          disabled: true
        - name: unused-parameter
        - name: unused-receiver

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - lll
        path: _test\.go
    paths:
      - .*\.gen\.go
      - .*\.pb\.go
      - ^.*\.(l|pb|y)\.go$
      - bin$
      - builtin$
      - examples$
      - genfiles$
      - internal/twitterapiio/sdk/sdk\.go
      - third_party$
      - vendor$
      - vendor/


formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
      module-path: github.com/aj-welch/ajwelch-x-app
    goimports:
      local-prefixes:
        - github.com/aj-welch/ajwelch-x-app

issues:
  max-same-issues: 50

run:
  allow-parallel-runners: true
  go: "1.25"
  issues-exit-code: 1
  tests: true
  timeout: 5m
