---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ajwelch-x-app
servers: 1
agents: 0
image: rancher/k3s:v1.28.4-k3s2
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: ajwelch-x-app-registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
  config: |
    mirrors:
      "localhost:5000":
        endpoint:
          - "http://ajwelch-x-app-registry.localhost:5000"
options:
  k3d:
    wait: true
    timeout: "120s"
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
